# Site settings
title: Evan's Blog
email: evantey15@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal blogging website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "localhost:4000" # the base hostname & protocol for your site
twitter_username: evantey14
github_username:  evantey14

# Build settings
markdown: kramdown
